### ISSUE TITLE
[NSKeyedUnarchiver initForReadingWithData:]: data is NULL PayUMoney IOS

### ISSUE THREAD

**Issue by nikhildange** [payu-intrepos/PayUMoney-IOS-SDK#4] opened 2017-02-06 06:32 UTC
I have integrated Payumoney framework in the iOS app.
Every time i present PUMMainVController, log showed
 ***** -[NSKeyedUnarchiver initForReadingWithData:]: data is NULL** 
thus  found out data of shared preference / NSUserdefault was lost [ 'null]'.
I searched through the net for the solution and synchronized user defaults where ever required instead relying on automatic synchronization but it didn't work.

**Comment by vipin04** [comment] 2017-02-08 07:25
Hi @nikhildange 

As far I can understand, your data in NSUserDefault is lost every time you try to present PUMMainVController. Is this the case?
If yes, please try our sample app and see if same thing happens there also?
I tried but could not replicate this issue.

**Comment by nikhildange** [comment] 2017-02-09 11:38
Hi @vipin04 ,

Thanks for Reply :)
Yes, I lose my data in NSUserDefault when presenting PUMMainVController in the app and logs 
*** -[NSKeyedUnarchiver initForReadingWithData:]: data is NULL error.

I tried to do store NSUserDefault data in Appdelegate Class & retrieve it in your sample app, had the same error. 

Below is log for your reference,

2017-02-09 17:05:21.201 PayUmoneySampleApp_ObjC[10305:489717] _AppDelegate_: **Value of Flag 'TRUE'**
2017-02-09 17:05:21.275 PayUmoneySampleApp_ObjC[10305:489717] _ViewController[viewDidLoad]_ **Value of Flag 'TRUE'**
2017-02-09 17:05:25.022945 PayUmoneySampleApp_ObjC[10305:489717] [MC] System group container for system
.
.
.
.
4d>
2017-02-09 17:05:31.127 PayUmoneySampleApp_ObjC[10305:489717] _ViewController[startPaymentTapped]_, **Value of Flag 'TRUE'**
2017-02-09 17:05:39.040 PayUmoneySampleApp_ObjC[10305:489717] _ViewController[transactinCanceledByUser]_ **Value of Flag (null)**

**Comment by vipin04** [comment] 2017-02-10 02:43
The issue is reproducible at our end. It will be fixed today. Expect an update by today EOD.

**Comment by vipin04** [comment] 2017-02-10 13:13
Issue has been fixed with [latest release](https://github.com/payu-intrepos/PayUMoney-IOS-SDK/releases/latest)

Please check and comment.

**Closed** 2017-02-11 02:42 UTC
Labels: bug
